# Generated by Django 4.2.7 on 2023-11-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_car', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coseguros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cos', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('prestaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drogueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_drog', models.CharField(max_length=20)),
                ('stock_drog', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_hab', models.CharField(max_length=50)),
                ('camas_hab', models.IntegerField()),
                ('camasdispo_hab', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obras_Sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('prestaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pac', models.CharField(max_length=30)),
                ('apellido_pac', models.CharField(max_length=15)),
                ('dni_pac', models.CharField(max_length=10)),
                ('domicilio_pac', models.CharField(max_length=50)),
                ('telefono_pac', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_per', models.CharField(max_length=30)),
                ('apellido_per', models.CharField(max_length=15)),
                ('dni_per', models.CharField(max_length=10)),
                ('domicilio_per', models.CharField(max_length=50)),
                ('telefono_per', models.CharField(max_length=12)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.pacientes')),
                ('personal_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Prescripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles_de_control', models.TextField()),
                ('medicamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.drogueria')),
                ('personal_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.personal_paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Obras_Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coseguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.coseguros')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.obras_sociales')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Internaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(auto_now_add=True)),
                ('fecha_egreso', models.DateField(auto_now=True)),
                ('hora_egreso', models.TimeField(auto_now=True)),
                ('habitacion_inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.habitaciones')),
                ('paciente_inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_internaciones.pacientes')),
            ],
        ),
    ]
