# Generated by Django 4.2.7 on 2023-11-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pac', models.CharField(max_length=50)),
                ('ape_pac', models.CharField(max_length=50)),
                ('dni_pac', models.CharField(max_length=50)),
                ('estado_pac', models.CharField(max_length=50)),
            ],
        ),
    ]
