# Generated by Django 4.2.7 on 2023-11-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_internaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='estado_pac',
            field=models.CharField(choices=[('1', 'Internado'), ('2', 'Alta'), ('3', 'Fallecido')], default='Espera', max_length=10),
        ),
    ]
