# Generated by Django 4.2.7 on 2023-11-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_internaciones', '0002_pacientes_estado_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='estado_pac',
            field=models.CharField(choices=[('1', 'Internado'), ('2', 'Alta'), ('3', 'Fallecido'), ('4', 'Espera')], default='4', max_length=10),
        ),
    ]
