# Generated by Django 4.2.7 on 2023-11-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_internaciones', '0006_remove_drogueria_descripcion_drog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drogueria',
            name='tipo_drog',
        ),
    ]
